### ISSUE TITLE
Found this in my log after upgrading to 2021.4

### ISSUE THREAD

**Issue by sylviepipi** [BazaJayGee66/homeassistant_cololight#12]
No 'version' key in the manifest file for custom integration 'cololight'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'cololight'

**Comment by reapingminer** [comment]
I am still running version 2021.3.4. And i also got this message.

Logger: homeassistant.loader
Source: loader.py:802
First occurred: 18:29:00 (1 occurrences)
Last logged: 18:29:00

No 'version' key in the manifest file for custom integration 'cololight'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'cololight'

**Comment by BazaJayGee66** [comment]
Thanks for letting me know! :)

This should now be resolved with version [v1.2.1](https://github.com/BazaJayGee66/homeassistant_cololight/releases/tag/v1.2.1).
