### ISSUE TITLE
Integration is not loaded in Home Assistant 2021.06 because of missing version in manifest.json

### ISSUE THREAD

**Issue by SmartHomeFanatic** [BazaJayGee66/homeassistant_cololight#15]
Hi!

Just updated to 2021.06. As the guys of HA require the integration's version in the manifest.json now it's not loaded anymore.

I added a random version number in my local manifest.json and it was loaded again.

**Comment by BazaJayGee66** [comment]
Thanks @SmartHomeFanatic,

This was added in version  [v1.2.1](https://github.com/BazaJayGee66/homeassistant_cololight/releases/tag/v1.2.1).

All releases can be found [here](https://github.com/BazaJayGee66/homeassistant_cololight/releases).

I've just updated HA to 2021.6.0 and can confirm it's working.

Thanks,

**Comment by SmartHomeFanatic** [comment]
Hi!
Don't know why but I was running a quite old version of the plugin.
Isn't this part of HACS anymore? Can't remember that I've seen any updating requests for the addon there.

**Comment by BazaJayGee66** [comment]
I'm not familiar with HACS sorry.

If you know of any HACS docs for supporting updating version please let me know, otherwise I'm happy to receive any PR's as well.

Thanks,

**Comment by BazaJayGee66** [comment]
I've had a look at the HACS docs, and for the time being this integration will only support [custom repositories](https://hacs.xyz/docs/faq/custom_repositories) in HACS.

This means as new versions are released you will need to update the URL to point to the new version.
