### ISSUE TITLE
Not finding it in integrations list

### ISSUE THREAD

**Issue by wout-junius** [BazaJayGee66/homeassistant_cololight#18]
This repo does not show up in the HACS
So I went for the manual method
I runned the command to the correct folder for the `custom_components` folder
I restarted and it did not show up in the integration list when trying to add a new integration.

Proof of installed in correct folder
![image](https://user-images.githubusercontent.com/17813748/149039442-cad51337-bfe7-4632-a8ad-af1d669246ba.png)

Proof of not finding it
![image](https://user-images.githubusercontent.com/17813748/149039561-116abc63-bd91-40e0-b4c8-5bc495f87a5f.png)

**Comment by BazaJayGee66** [comment]
This might be due to the older version `1.2.0`.

I have updated the README to point to the latest version `1.2.3`
```
wget https://github.com/BazaJayGee66/homeassistant_cololight/releases/download/v1.2.3/cololight.zip
```

Please try downloading again with the latest version, and ensuring that Home Assistant is restarted after adding it to the `custom_components` directory.

**Comment by wout-junius** [comment]
Yes, that fixed it, thank you!
