### ISSUE TITLE
Not showing up in 'integrations' after install through HACS

### ISSUE THREAD

**Issue by tic226n** [BazaJayGee66/homeassistant_cololight#19]
I've installed the integration through HACS according to the documentation and restarted the HA host. Afterwards when saerching for  the integration in 'Configuration > Devices' i couldn't find an entry named Lifesmart cololight. The logs were clear so i restarted again, all to no avail. However, when trying the same procedure with the homeassistant android app on my phone it worked as intended. I noticed that the entry for 'Lifesmart cololight' in the search list didn't have a favicon/icon beside its entry, only a placeholder with the text 'icon not available'. Perhaps that's why the entry doesn't show up in the browser (missing icon), there have been UI errors like that in homeassistant before, like entries or buttons not showing up. 

HAOS host version: core-2021.12.9 / Home Assistant OS 7.1
HACS version: 1.19.3

**Comment by BazaJayGee66** [comment]
I'm not very familiar with HACS sorry, does it provide any logs, or are there any error logs in HA?

The image hasn't been added, so it's expected to see `icon not available`.

**Comment by tic226n** [comment]
I just tried it again and now it does show up in the list of integrations although i haven't touched anything since yesterday evening when i opened this issue, weird. (HA is such a mess, it is driving me nuts..)
False alarm, thank you for getting back to me
