### ISSUE TITLE
Great work - minor fix - update manifest to show correct version

### ISSUE THREAD

**Issue by ballakers** [BazaJayGee66/homeassistant_cololight#20]
Not much of an issue but version in manifest doesn't match version of actual integration.  Thought I was behind on version but I see the manifest here is the same. Also just wanted to say been using this for a while and works great (IP address of light changed today which made me revisit the GitHub to check effects etc - easy fix though) - many kudos!

**Comment by BazaJayGee66** [comment]
Thanks!
This has been resolved with the new version `v1.3.0`
