### ISSUE TITLE
Pro hexagon not following commands

### ISSUE THREAD

**Issue by BorjaLL** [BazaJayGee66/homeassistant_cololight#29]
I have a couple of plus and pros
the pros when using the service light.on in an automation are not setting the color. the brightness works ok.
I've tried RGB and collar name but it is not changing out of whichever mode it is in.

do you have any idea why this is?
the plus do respond as expected to the service call

**Comment by BazaJayGee66** [comment]
Are you able to share the automation you're using for the pros?
