### ISSUE TITLE
HA does read Cololight's state after restart

### ISSUE THREAD

**Issue by SmartHomeFanatic** [BazaJayGee66/homeassistant_cololight#3]
Hi there!
Thanks for maintaining the addon! Really appreciate that I can integrate the cololight into HA.

My issue is that HA does not read the Cololights state after restart. So when the Cololight is already on it crashes when turned on in HA. I then have to pull the plug to restart it.

Anyone experiencing that?

**Comment by BazaJayGee66** [comment]
Currently the component doesn't have a way of receiving state from the cololight device itself, however it should restore the last known state in HA after HA is restarted.

I'm not sure what you mean by "it crashes".
> So when the Cololight is already on it crashes when turned on in HA. I then have to pull the plug to restart it.

Does the Cololight device crash, and has to be restarted, or are you referring to HA?

**Comment by SmartHomeFanatic** [comment]
I am only using HA to control the Cololight. After restarting HA the switch for the Cololight in HA is always off, so the state isn't restored.

When crashing, the Cololight gets a lot brighter and immediately stops animating. Only solution for that is to pull its plug then.

**Comment by BazaJayGee66** [comment]
Are you able to confirm if this is still occurring with the latest code changes?

**Comment by SmartHomeFanatic** [comment]
Hi!
Seems good now. Sometimes the brightness changes with HA restarting but I can totally live with that.
Thanks for the awesome fix!
