### ISSUE TITLE
Can not add repository to HA

### ISSUE THREAD

**Issue by benkolle1** [BazaJayGee66/homeassistant_cololight#34]
Hi there,

I have followed the instructions but I'm unable to add the rpository to Home Assistant. Can you please let me know if I'm using the wrong URL. The one I'm using is https://github.com/BazaJayGee66/homeassistant_cololight.git

![image](https://github.com/BazaJayGee66/homeassistant_cololight/assets/152096239/1a7227ed-883e-41a1-be81-a6c3f562effa)
![Screenshot 2023-11-27 211642](https://github.com/BazaJayGee66/homeassistant_cololight/assets/152096239/33bf177d-03a7-4d1e-8b60-1a33b3c051cd)

**Comment by BazaJayGee66** [comment]
It looks like you're trying to install this custom component via [home assistant add-ons](https://www.home-assistant.io/hassio/installing_third_party_addons/).

Unfortunately add-ons doesn't support adding of custom components.

The [README](https://github.com/BazaJayGee66/homeassistant_cololight/blob/master/README.md) offers some installation methods, either via [hacs](https://hacs.xyz/), or manually copying the files into your Home Assistant configuration directory.

**Comment by benkolle1** [comment]
Hi, 

 

Thank you so much for the information. I got this going, and it works great. 

 

Ben
