### ISSUE TITLE
after upgrading to 2024.2.0 I spotted this in my ha log, deprecated supported features values which will be removed in HA Core 2025.1

### ISSUE THREAD

**Issue by JustAro01** [BazaJayGee66/homeassistant_cololight#37]
After upgrading HA to 2024.2.0. I spotted this warning message in my home assistant log:

Logger: homeassistant.components.light
Source: components/light/__init__.py:1242
Integration: Licht ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: 14:34:37 (1 occurrences)
Last logged: 14:34:37
Entity None (<class 'custom_components.cololight.light.coloLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature.EFFECT|17: 21> and color modes, please create a bug report at https://github.com/BazaJayGee66/homeassistant_cololight/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by BazaJayGee66** [comment]
Thanks for raising.

This has been resolved with [v2.0.3](https://github.com/BazaJayGee66/homeassistant_cololight/releases/tag/v2.0.3)
