### ISSUE TITLE
Fails to be added as a custom repository

### ISSUE THREAD

**Issue by JeffHerb** [BazaJayGee66/homeassistant_cololight#7]
I'm very new to home assistant so I'm not sure what I can provide to help, but when attempting to add the custom repository I get:

`20-10-04 15:13:52 INFO (MainThread) [supervisor.store.git] Clone add-on https://github.com/BazaJayGee66/homeassistant_cololight.git repository
20-10-04 15:13:53 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/5a603ff2/repository.json: [Errno 2] No such file or directory: '/data/addons/git/5a603ff2/repository.json'
20-10-04 15:13:53 WARNING (MainThread) [supervisor.store.data] Can't read repository information from /data/addons/git/5a603ff2/repository.json`

This is running on a raspberry pi 4, with 4GB of RAM and a 32 GB sd card.

Please let me know if there is anything else I can provide.

**Comment by BazaJayGee66** [comment]
Thanks @JeffHerb,

Which install method are you are you attempting, and which Home Assistant version are you running?

**Comment by BazaJayGee66** [comment]
Doing a little digging, looks like you might be attempting to install this custom component via [home assistant add-ons](https://www.home-assistant.io/hassio/installing_third_party_addons/).
Would this be correct?

Unfortunately add-ons doesn't support adding of custom components.

The [README](https://github.com/BazaJayGee66/homeassistant_cololight/blob/master/README.md) offers some installation methods, either via [hacs](https://hacs.xyz/), or manually copying the files into your Home Assistant configuration directory.

Let me know if you have trouble with either of these, feedback always welcome.

Welcome to the HA community :)

**Comment by JeffHerb** [comment]
I'm running the latest version of Home Assistant. Let me take another look and I will let you know. Sorry, I'm very new to HA.

**Comment by BazaJayGee66** [comment]
Hey @JeffHerb,

Have you had any luck with this?

**Comment by JeffHerb** [comment]
Yes, I was able to get it working, thank you for the assistance.
