### ISSUE TITLE
Group management

### ISSUE THREAD

**Issue by BornTKill** [BazaJayGee66/homeassistant_cololight#8]
Hi!

First of all, I would like to congrats you for maintaining this great addon. Keep the good job !

I have 2 cololights that are grouped, can you help me to create a group in HA with the same options that are available for single light. At least, on/off, color picker, default effects.

thanks you for your help.

**Comment by BazaJayGee66** [comment]
Hey @BornTKill,

Glad you're liking it.

How are you currently grouping the lights, and what behaviour are you seeing?

Have you tried something like the [Light Group](https://www.home-assistant.io/integrations/light.group/)?

**Comment by BornTKill** [comment]
@BazaJayGee66 

i have only group 2 cololights in the official app. I will try your proposal and let you know.

**Comment by BornTKill** [comment]
Dear @BazaJayGee66 !

works like a charm ! Thank you
